### ISSUE TITLE
On Firefox plays the first track only from each album in Wishlist

### ISSUE THREAD

**Issue by AzMandius** [AFlowOfCode/bandcamp-streamer#1]
I thought this is the perfect add-on until i noticed that on Firefox it plays the first track only from each album in Wishlist. So disappointing.

Did not try on Chrome yet.

**Comment by AFlowOfCode** [comment]
@AzMandius That is just how it is on Bandcamp, this extension does not attempt to circumvent that. You have to purchase albums to stream everything from your collection page.
