### ISSUE TITLE
Filtered wishlist cannot be played continuously

### ISSUE THREAD

**Issue by vzellweg** [AFlowOfCode/bandcamp-streamer#3]
Browser: Chrome 94.0.4606.71

Steps to reproduce:
1. Go to your wishlist
2. Take an artist's name who has multiple tracks in your wishlist and enter it in the "Search your wishlist" input box
3. Play the first track - Observe how the bandcamp-streamer controls are not displayed

**Comment by AFlowOfCode** [comment]
Thanks for bringing this up. The extension doesn't currently support that, but it should be doable without too much trouble. It's on my list now!

**Comment by AFlowOfCode** [comment]
This is now implemented & available in the latest release 👍
