### ISSUE TITLE
Collection player no longer initializing nor visible

### ISSUE THREAD

**Issue by seedy** [AFlowOfCode/bandcamp-streamer#5]
# Description

Streamer extension's player is no longer displayed when I play a track from my collection. 

I notice there's an error in console during initialization. Can it be the root cause of the player not loading anymore?

Here's my console

![image](https://user-images.githubusercontent.com/3367393/150499282-5eab4382-1610-49f3-89f0-85f7b4981e29.png)

When reloading with a breakpoint on the line which threw an error, I notice the following:

![image](https://user-images.githubusercontent.com/3367393/150500151-517150d5-84ad-41d7-928a-07f0333effdd.png)

`tracklist[item_key] // undefined`

I think for a safer run, you could maybe have a fallback computation:
```
const trackGroup = tracklist[item_key]
let track = trackGroup ? trackGroup[0] : undefined;
```

WDYT?

**Comment by AFlowOfCode** [comment]
Hello, that error is indeed why the player didn't show up. Thanks for pinpointing the issue, you are quite right about using a safer check for the track there & I have updated it accordingly. Naturally a missing track should not nuke the entire playlist.

This is fixed on v1.3.2, if you are using FF it is already released & Chrome will follow shortly.
