### ISSUE TITLE
[FR] playerctl next

### ISSUE THREAD

**Issue by bonnebulle** [AFlowOfCode/bandcamp-streamer#6]
Hello thanks for helping playing good music on the internet
Am on Linux, using Firefox
And would like to use [playerctl](https://github.com/altdesktop/playerctl) to play next or previous track from everywhere (with a keyboard shortcut use)
Do you think your module can do it ?
( implement media playing list to system (bus) )
Thanks again

**Comment by AFlowOfCode** [comment]
Hey, thanks & glad you find it useful. That is an interesting idea. I'll have to do some research to see how feasible & how much effort it would be.

**Comment by bonnebulle** [comment]
Yep, of course.... I keep searching
It's most an OS/Browser integration problem
But maybe we can find a wa
you do a the half of the work here 
(adding previous/next buttons + playlist)
Thanks again

**Comment by bonnebulle** [comment]
Working great with de default player in Tags like this one : 
https://bandcamp.com/tag/experimental
I do a little script for notify...
https://gist.github.com/bonnebulle/93b148d9f391ed3d2a98f0ed7ce5a71c
See you next time

**Comment by bonnebulle** [comment]
New BC design
All is now outdated
It was good to play with it
