### ISSUE TITLE
Seek through playing track

### ISSUE THREAD

**Issue by digipakman** [AFlowOfCode/bandcamp-streamer#7]
Using the firefox version right now, just wondering if adding functionality to seek through/skip to different times in a playing track is on the roadmap or feasible to do. Great extension!

**Comment by AFlowOfCode** [comment]
Thanks, glad you find it useful. 

You're talking about on the feed page right? Yeah that would be a cool addition. I'll look into how complicated it would be since it's a different type of player than the collection/wishlist ones which do already have seek.

**Comment by digipakman** [comment]
That's exactly it, seeking on the feed page would be really useful, even if it takes the form of +\- 10 secs buttons or something in that wheelhouse. Appreciate it being considered!

**Comment by AFlowOfCode** [comment]
Ok, I took your suggestion & did it the simple way just to get it out there. On the feed player there is now a "seek" row with << and >> buttons which skip back & forth 10 seconds for the currently playing track. 

New extension version is 1.5.0 which is now available for Firefox. Chrome usually takes 12 - 24 hours to approve new versions so if you don't see it immediately it should show up shortly.

**Comment by digipakman** [comment]
Awesome, thank you so much for making bandcamp way better
